name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - hydra-core=1.3.2
  - matplotlib=3.9.2
  - pandas=2.2.3
  - pip=24.3.1
  - scikit-learn=1.5.2
  - jupyterlab=4.3.0
  - pip:
      - mlflow==2.17.2
      - wandb==0.18.6