name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.0
  - pip=24.3.1
  - requests=2.32.3
  - scikit-learn=1.5.2
  - pip:
      - mlflow==2.27.2
      - wandb==0.18.6
      - git+https://github.com/hoffmann17/build-ml-pipeline-for-short-term-rental-prices.git#egg=wandb-utils&subdirectory=components
