name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas=2.2.3
  - pytest=8.3.3
  - scipy=1.14.1
  - pip=24.3.1
  - pip:
      - mlflow==2.17.2
      - wandb==0.18.6
