name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - hydra-core=1.3.2
  - matplotlib=3.9.2
  - pandas=2.2.3
  - jupyterlab=4.3.0
  - pip=24.3.1
  
  - pip:
      - cmake
      - pyarrow #--config-settings=build_ext="-DPYARROW_BUILD_FLIGHT=OFF" --config-settings=build_ext="-DPYARROW_BUILD_DATASET=OFF" --config-settings=build_ext="-DPYARROW_BUILD_ACERO=OFF"
      - mlflow==2.17.2
      - wandb==0.18.6
