name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=24.3.1
  - requests=2.24.0
  - pyarrow
  - cmake
  - pip:
      - mlflow==2.17.2
      - wandb==0.18.6
      - git+https://github.com/hoffmann17/build-ml-pipeline-for-short-term-rental-prices.git#egg=wandb-utils&subdirectory=components
